
#:import utils kivy.utils

<PongBall>:
    size : 50, 50
    canvas:
        Color:
            rgba:utils.get_color_from_hex("#2A2F44")

        Ellipse:
            pos: self.pos
            size: self.size


<PongPaddle>:
    size : 15,200
    canvas:
        Color:
            rgba:utils.get_color_from_hex("#5f2f11")

        Rectangle:
            pos: self.pos
            size: self.size

<PongGame>:
    ball: pong_ball
    player1: player_left
    player2: player_right

    canvas:

        Color:
            rgba: 0, 0, 1, 1    # Blue

        Rectangle:
            #pos: self.center_x-1,0 is pixel location x and y
            pos: self.center_x-1,0
            size: 10,self.height  #define width and height of a seperation line


    #Player 1 Score
    Label:
        font_size : 70
        center_x: root.width/4
        top: root.top -50
        text : str (root.player1.score)
        #text : "0"

    #Player 2 Score
    Label:
        font_size : 70
        center_x: root.width * 3/4
        top: root.top -50
        text : str(root.player2.score)
        #text : "0"

    PongBall:
        id: pong_ball
        center : self.parent.center

    PongPaddle:
        id: player_left
        x: root.x
        center_y: root.center_y

    PongPaddle:
        id: player_right
        x: root.width - self.width
        center_y: root.center_y
